INSERT INTO Files (filename, filesize, directory) VALUES ('mayhem-cmake-example':256, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zshrc-e':239, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.stack':320, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('SATTicket.pdf':225866, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Cisco Packet Tracer 8.0.0':320, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.Rhistory':0, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.config':224, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Music':256, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.serverauth.14844':63, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('ALL.txt':1192, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('wordlist(AutoRecovered).xlsx':66787, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('load_lab1.sql':3349, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('IMG_0003.JPG':501181, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.condarc':40, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.docker':480, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('resume.tex':6178, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('MLB Divisions':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.anyconnect':671, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.serverauth.6949':63, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.vim':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-13 at 6.12.43 PM.png':228615, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('go':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('matlab_crash_dump.44389-1':3312, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Homework_12_Sudoku.py':0, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('VirtualBox VMs':192, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.lldb':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('test':192, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('get-docker.sh':18565, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.angular-config.json':89, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.tooling':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('venple.err':92, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('txt.txt':3708, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('university.xlsx':11450, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.cabal':224, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Untitled.ipynb':72, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('learning-to-use-git':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('q.pub':593, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zshrc':389, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Dockerfile':58, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.packettracer':440, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.serverauth.717':71, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('OneDrive':3200, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Prithvi Arunshankar - CIR & Gatsby Synthesis Essay Outline EXAMPLE.pdf':80229, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.local':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.psql_history':4679, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Creative Cloud Files':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('C++ Practice':192, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Pictures':320, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.pylint.d':320, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('path':64, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('resume':320, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zprofile':42, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('node_modules':8480, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.nvm':992, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('shell-programs':192, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.mayhem':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zsh_profile':23, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Q1':800, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('resume.pdf':119489, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Job Fair Flyers 2019 1.pdf':1510066, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zsh_history':23694, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.ipython':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Desktop':2400, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Library':3840, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.matplotlib':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('huffman-encoding':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('prithvi.arun27@gmail.com Creative Cloud Files':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.serverauth.4059':142, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.lesshst':20, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('texput.log':733, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.oracle_jre_usage':192, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Parallels':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-17 at 9.56.44 PM.png':49726, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Creative Cloud Files prithvi_arun@outlook.com 96bcc3dd64d1001bbd2880fe11e3a02fba84f35335cbad7c804603aef11aa385':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('iPhone Programming.pdf':4519200, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Prithvi Era':288, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-03-22 at 5.57.49 PM.png':134887, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Prithvi_Arunshankar_Reume_06_08_2022.pdf':5321945, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('My Junk':64, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('matlab_crash_dump.31936-1':5210, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.bash_profile.pysave':368, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Old Stuff':30592, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('README.md':1341, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.android':64, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.cups':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Sites':64, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.serverauth.19365':71, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.bash_sessions':2080, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-04 at 12.14.10 PM.png':542445, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-16 at 9.09.15 PM.png':173602, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('PacketTracer7':288, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-01 at 3.11.30 PM.png':35199, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Transcripts.pdf':180694, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('PycharmProjects':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Public':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('arunshankarv@hotmail.com Creative Cloud Files':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('getting-started':544, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.gitignore':32, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('package-lock.json':296104, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('package.json':109, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-03-27 at 10.12.48 AM.png':43250, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.idlerc':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.cisco':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.RData':11216, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('foo':32, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('googlelogo_light_color_272x92dp.png':17616, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-13 at 6.13.03 PM.png':374293, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('not.txt':2834, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.anaconda':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('TimeTable.xlsx':10262, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('MikeSherm.jpg':43619, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.ssh':256, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Movies':320, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Game 1.game':1553, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.vimrc':421, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('testdir':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Applications':192, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('PyQt5 Demonstrations':224, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.ghc':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.gradle':224, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('hackathon-resources':448, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('resume.aux':32, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.Rapp.history':2311, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('opt':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.Trash':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('banhammer.c':0, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('resume.log':8261, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zoomus':64, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('prihu.pdf':5279182, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.ipynb_checkpoints':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-10 at 4.49.55 PM.png':1146338, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.jupyter':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zcompdump':49250, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('github-classroom':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.ghcup':416, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.npm':224, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('cs2b prep':288, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('foo1.txt':16, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Documents':224, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zcompcache':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('tst':352, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('PrithviFluImmunization3:10:19.pdf':126211, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('query1.sql':147, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.git':288, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.vscode':160, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('prog_packages':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.m2':96, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.bash_profile':1259, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('foo2.txt':16, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('hw.txt':320, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.swiftpm':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('getfileinfo.sh':572, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.Xauthority':1214, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('RESUME PRITHVI A.docx':14891, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Downloads':14912, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.python_history':294, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.cache':224, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('resume.synctex.gz':10362, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.gitconfig':124, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('matlab_crash_dump.61767-1':3125, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('Profile Photo.webloc':319, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('q':2675, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.putty':128, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('Screen Shot 2019-04-17 at 12.01.03 AM.png':13998, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.bash_history':16360, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.viminfo':43460, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.zsh_sessions':192, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('create_lab1.sql':1205, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('git':14976, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('a.java':0, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.aliases':43, 'no');
INSERT INTO Files (filename, filesize, directory) VALUES ('.conda':64, 'yes');
INSERT INTO Files (filename, filesize, directory) VALUES ('.venple':1193, 'no');
